### ISSUE TITLE
language fallback?

### ISSUE THREAD

**Issue by agitator** [collective/collective.vdexvocabulary#1]
if the language is defined within the vdex, but not available in the portal
 the widget (at least with the c.dynatree) shows "(unnamed term)" for the term.

shouldn't there be a fallback to a main language, or at least show the keys?

**Comment by jensens** [comment]
if the vdex does not provide the configured language its at the moment a problem. 

solution: provide a default_language attribute for the directive (since vdex lacks of such a settings).

also: check if "(unnamed term)" comes back from underlying imsvdex and replace it with something more meaningful.
